### ISSUE TITLE
JSONDecodeError while populating player data

### ISSUE THREAD

**Issue by avadhanij** [mpope9/nba-sql#19]
Ran into the following issue while using the `create_postgres.sh` shell script.

```
nbasql ❯ ./scripts/create_postgres.sh
Connecting to postgres database.
Initializing schema.
Populating team data
team Table Loading |██████████████████████████████| 100.0%
Populating player data
Traceback (most recent call last):------------------| 0.0%
  File "/Users/avadhanij/dev/nbasql/nba-sql/stats/nba_sql.py", line 259, in <module>
    main()
  File "/Users/avadhanij/dev/nbasql/nba-sql/stats/nba_sql.py", line 105, in main
    populate_base_tables(
  File "/Users/avadhanij/dev/nbasql/nba-sql/stats/nba_sql.py", line 221, in populate_base_tables
    player_requester.add_player(season_id)
  File "/Users/avadhanij/dev/nbasql/nba-sql/stats/player.py", line 49, in add_player
    response = requests.get(url=self.player_info_url, headers=headers, params=params_str).json()
  File "/Users/avadhanij/.virtualenvs/nbasql/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Not entirely clear if it's because of some change in format of incoming data.

**Comment by mpope9** [comment]
Strange. I'll give it a run this week and see if I can repro it.

**Comment by mpope9** [comment]
@avadhanij Cool queries on your branch. Do you mind if I add some to the wiki as examples?

**Comment by avadhanij** [comment]
First off, my bad, I should have seen the link to your wiki. I am a bit surprised that you are storing the sql dump as a release. Isn't that data proprietary?

Anyway, I am not entirely sure what you would add from here to you wiki, but sure, go ahead.

**Comment by mpope9** [comment]
🤫 I'm not sure. If I get asked to remove the file, then I will.

The 50/40/90 query caught my eye, if I do end up adding it I will credit you.

**Comment by avadhanij** [comment]
I think you have me confused with some one else :). I haven't even been able to get this to run yet. 

My first two attempts resulted in errors, that I created issues out of. I forked your repo to work on those myself.

**Comment by mpope9** [comment]
@avadhanij Yes, it looks like I have my mistake. I can get around to these issues this weekend, but if you have figured them out yourself I'd gladly accept a PR.

**Comment by avadhanij** [comment]
I don't think so. I was not able to reproduce this issue.

Which may be because I have mainly been using it with one season (2020-21). This showed up when I tried to run it with all seasons. I will give that a try again.

**Comment by mpope9** [comment]
Huh, I am also getting this when importing from the beginning, but `2020-21` is fine. I'll debug this further, maybe they've invalidated the last season.

**Comment by mpope9** [comment]
Oh no, this is caused by rate limiting, I believe. We're getting 502 errors. Increasing the time between requests to .7 seconds made the error occur later, looking at the responses. I wonder if it is time to understand how this behaves in AWS (if the NBA has blocked whatever IP block that AWS uses), and distribute each season to a unique machine.

Regardless, I'll close this issue once I merge that change, and link this to the distribute issue.

**Comment by mpope9** [comment]
Increasing the timeout didn't work for the earlier seasons. I wonder if we should change the default behavior to just load the current season.

**Comment by avadhanij** [comment]
So you are saying that at this time, a user can't generate a DB with all the seasons? 

> I wonder if we should change the default behavior to just load the current season

This isn't a bad idea. Make it incremental, so that user can choose which seasons are important.

**Comment by mpope9** [comment]
Yes, it appears so. I can successfully load `2020-21`, but starting from the `1996-97` season the endpoint returns a 400 error. I'm not sure if the params that the player endpoint accepts has changed, I have this weekend free so I'll dig in to it before just defaulting to the current season. Its a better user experience loading the most recent data than seeing an error on first run, though.

**Comment by mpope9** [comment]
Tried to get back to this issue since I've been making some changes. For `1996-97` I'm now seeing
```
./scripts/create_postgres.sh
Connecting to postgres database.
Initializing schema.
Populating base tables
Populating team data
team Table Loading |██████████████████████████████| 100.0%
Populating player data
player Table Loading |██████████████████████████████| 100.0%
Loading event types.
Loading player_game_log season Data |██████████████████████████████| 100.0% This one will take a while...
Loading cached game table.
Traceback (most recent call last):
  File "stats/nba_sql.py", line 392, in <module>
    main()
  File "/Users/pope/Projects/nba-sql/venv/lib/python3.8/site-packages/gooey/python_bindings/gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "stats/nba_sql.py", line 238, in main
    game_builder.populate_table(game_set)
  File "/Users/pope/Projects/nba-sql/stats/game.py", line 54, in populate_table
    new_row['team_id_winner'] = teams[teams.index(entry.loser) - 1]
ValueError: 1610612766 is not in list
```

Which seems odd. Not a JSONDecodeError, but we have a team that might not exist in the list of teams?

**Comment by mpope9** [comment]
I believe this has been fixed. The NBA API changed the playergamelogs columns (I think). Making that follow the other tables' dynamic api access has fixed this problem, can load from 2010-2021 now. Closing out this issue.

**Comment by mpope9** [comment]
(closed by https://github.com/mpope9/nba-sql/pull/55)
